package EvenFibonacci;

/**
 * Author: Alex Yang
 * Date: 12/21/14
 * Dependencies:
 * - N/A
 * Description:
 * - Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * Solution:
 * - N/A
 */
public class EvenFibonacci {
  public static void main(String args[]) {
    System.out.println(fib());
  }

  static int fib() {
    int total = 0;
    int n = 0;
    int n1 = 1;
    int n2 = 1;
    while (n < 4000000) {
      n = n1 + n2;
      n2 = n1;
      n1 = n;

      if (n%2 == 0) total += n;
    }


    System.out.println(n);
    return total;
  }
}
